sudo: false
notifications:
  email: true
language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12"
cache:
  directories:
    - node_modules
install:
  - node --version
  - npm --version
  - npm install
  - npm install -g grunt
before_script:
  - npm run build
script: npm test
