sudo: false
notifications:
  email: true
language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - node_modules
install:
  - node --version
  - npm --version
  - npm install
  - npm install -g grunt
  - npm install -g docco
script: npm test
after_success: npm run coverage
