sudo: false
notifications:
  email: true
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "node"
  - "iojs"
install:
  - node --version
  - npm --version
  - npm install
before_script:
  - node_modules/grunt/bin/grunt
script: npm test
