sudo: false
language: cpp
notifications:
  email: false
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"
install:
  - clone https://github.com/Peterfurax/streamVideoSrv.git
  - nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm install
script: node server.js
